# Generated by Django 2.2.11 on 2020-06-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainpost',
            name='pic',
            field=models.ImageField(default='home/home.jpg', upload_to='home/%Y%m%d/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='domainpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='domainpost',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='domainpost',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='domainpost',
            name='domain',
            field=models.CharField(max_length=100, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='domainpost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='domainpost',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
