# Generated by Django 2.2.11 on 2020-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_auto_20200620_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainpost',
            name='isShow',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
