# Generated by Django 2.2.11 on 2020-06-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_domainpost_isshow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainpost',
            options={'ordering': ('-created',), 'verbose_name': '网址导航', 'verbose_name_plural': '网址导航'},
        ),
    ]
