# Generated by Django 2.2.11 on 2020-04-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200415_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='createTime', verbose_name='slug'),
        ),
    ]
