# Generated by Django 2.2.11 on 2020-04-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200416_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-createTime',)},
        ),
    ]
