# Generated by Django 2.2.11 on 2020-04-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish',)},
        ),
    ]
