# Generated by Django 2.2.11 on 2020-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_remove_article_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-createTime',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='createTime', verbose_name='slug'),
        ),
    ]
