# Generated by Django 2.2.11 on 2020-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20200416_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
