# Generated by Django 2.2.11 on 2020-04-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20200416_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, unique_for_date='createTime'),
        ),
    ]
