# Generated by Django 2.2.11 on 2020-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20200416_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
