# Generated by Django 2.2.11 on 2020-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20200416_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
