# Generated by Django 2.2.11 on 2020-04-17 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20200417_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
