# Generated by Django 2.2.11 on 2020-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20200417_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, default='uuiduuid4', max_length=64, unique=True),
        ),
    ]
