# Generated by Django 2.2.11 on 2020-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20200417_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsdatetimefield', unique=True),
        ),
    ]
