# Generated by Django 2.2.11 on 2020-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20200417_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
