# Generated by Django 2.2.11 on 2020-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_auto_20200417_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=140, unique=True, unique_for_date='createTime'),
            preserve_default=False,
        ),
    ]
