# Generated by Django 2.2.11 on 2020-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='3', max_length=200, unique=True),
        ),
    ]
