# Generated by Django 2.2.11 on 2020-04-18 11:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20200417_1219'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objec', django.db.models.manager.Manager()),
            ],
        ),
    ]
