# Generated by Django 2.2.11 on 2020-04-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20200418_1124'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
