# Generated by Django 2.2.11 on 2020-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_auto_20200418_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='允许评论'),
        ),
    ]
