# Generated by Django 2.2.11 on 2020-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_auto_20200418_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='3', max_length=200, unique=True, verbose_name='唯一码字'),
        ),
    ]
