# Generated by Django 2.2.11 on 2020-05-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
