# Generated by Django 2.2.11 on 2020-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0034_remove_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lifeOrStudy',
            field=models.CharField(default='学无止境', max_length=10, verbose_name='所属总分类'),
        ),
    ]
