# Generated by Django 2.2.11 on 2020-06-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_auto_20200612_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lifeOrStudy',
            field=models.CharField(choices=[('学无止境', '学无止境'), ('慢生活', '慢生活')], default='学无止境', max_length=10, verbose_name='所属总分类'),
        ),
    ]
